/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.safapharma.Home;

import com.safapharma.Helpers.Constants;
import static com.safapharma.Helpers.Constants.BUTTON_CUSTOMER_LABEL;
import static com.safapharma.Helpers.Constants.BUTTON_SALES_LABEL;
import static com.safapharma.Helpers.Constants.BUTTON_SUPPLIER_LABEL;
import com.safapharma.Helpers.IconConstants;
import com.safapharma.Main.MainWindow;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import static com.safapharma.Helpers.Constants.FONT_SIZE_14_CALIBRI;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Natasha Malik
 */
public class SidePanel extends javax.swing.JPanel {

    private MainWindow manager;
    private JLabel buttonCustomer;
    private JLabel buttonSales;
    private JLabel buttonSupplier;
    private JLabel buttonStock;
    private JLabel buttonMedicine;
    private final static int WIDTH_PANEL = 130;

    /**
     * Creates new form SidePanel
     */
    public SidePanel(MainWindow manager) {
        initComponents();
        this.manager = manager;
        initUI();
        setListeners();
    }

    private void initUI() {

        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBackground(Color.gray);
        setPreferredSize(new Dimension(WIDTH_PANEL, HEIGHT));
        setBorder(BorderFactory.createMatteBorder(0, 0, 0, 4, Color.darkGray));

        buttonCustomer = new SidePaneLabel(BUTTON_CUSTOMER_LABEL, new ImageIcon(getClass().getResource(IconConstants.CUSTOMER_ICON)));
        buttonSales = new SidePaneLabel(BUTTON_SALES_LABEL, new ImageIcon(getClass().getResource(IconConstants.SALES_ICON)));
        buttonSupplier = new SidePaneLabel(BUTTON_SUPPLIER_LABEL, new ImageIcon(getClass().getResource(IconConstants.SUPPLIER_ICON)));
        buttonStock = new SidePaneLabel(Constants.BUTTON_STOCK_LABEL, new ImageIcon(getClass().getResource(IconConstants.STOCK_ICON)));
        buttonMedicine = new SidePaneLabel(Constants.BUTTON_MEDICINE_LABEL, new ImageIcon(getClass().getResource(IconConstants.MEDICINE_ICON)));

        add(buttonCustomer);
        add(buttonMedicine);
        add(buttonSales);
        add(buttonStock);
        add(buttonSupplier);
    }

    private void setListeners() {
        buttonSupplier.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                buttonSupplierActionPerformed(e);
            }
        });
        buttonCustomer.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                buttonSupplierActionPerformed(e);
            }
        });
        buttonMedicine.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                buttonSupplierActionPerformed(e);
            }
        });
        buttonSales.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                buttonSupplierActionPerformed(e);
            }
        });
        buttonStock.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                buttonSupplierActionPerformed(e);
            }
        });
    }

    private void buttonSupplierActionPerformed(MouseEvent e) {
        manager.createSupplierPanel();
        manager.showSupplierPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private class PanelButton extends JButton {

        public PanelButton(String text, ImageIcon icon) {
            super(text, icon);
//            setPreferredSize(new Dimension(138, HEIGHT));
            setMinimumSize(new Dimension(WIDTH_PANEL, 55));
            setMaximumSize(new Dimension(WIDTH_PANEL, 55));
            setBorder(BorderFactory.createEmptyBorder(6, 16, 6, 6));
            setHorizontalAlignment(SwingConstants.LEFT);
            setVerticalAlignment(SwingConstants.CENTER);
            setHorizontalTextPosition(SwingConstants.RIGHT);
            setFont(FONT_SIZE_14_CALIBRI);
        }

    }

    private class SidePaneLabel extends JLabel {

        public SidePaneLabel(String text, ImageIcon icon) {
            super(text, icon, JLabel.HORIZONTAL);
            setMinimumSize(new Dimension(WIDTH_PANEL, 55));
            setMaximumSize(new Dimension(WIDTH_PANEL, 55));
            setBorder(BorderFactory.createCompoundBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder(EtchedBorder.RAISED)));
            setHorizontalAlignment(LEFT);
            setHorizontalTextPosition(RIGHT);
            setVerticalTextPosition(CENTER);
            setFont(FONT_SIZE_14_CALIBRI);
            setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }

    }
}
