/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.safapharma.Home;

import com.safapharma.Helpers.Constants;
import static com.safapharma.Helpers.Constants.BUTTON_CUSTOMER_LABEL;
import static com.safapharma.Helpers.Constants.BUTTON_SALES_LABEL;
import static com.safapharma.Helpers.Constants.BUTTON_SUPPLIER_LABEL;
import com.safapharma.Helpers.IconConstants;
import com.safapharma.Main.MainWindow;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import static com.safapharma.Helpers.Constants.FONT_SIZE_14_CALIBRI;
import static com.safapharma.Helpers.Constants.FONT_SIZE_14_CALIBRI;
import javax.swing.BorderFactory;
import javax.swing.border.CompoundBorder;

/**
 *
 * @author Natasha Malik
 */
public class SidePanel extends javax.swing.JPanel {

    private MainWindow manager;
    private JButton buttonCustomer;
    private JButton buttonSales;
    private JButton buttonSupplier;
    private JButton buttonStock;
    private JButton buttonMedicine;

    /**
     * Creates new form SidePanel
     */
    public SidePanel(MainWindow manager) {
        initComponents();
        this.manager = manager;
        initUI();
        setListeners();
    }

    private void initUI() {

        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBackground(Color.gray);
        setPreferredSize(new Dimension(140, HEIGHT));
        setBorder(new CompoundBorder(BorderFactory.createMatteBorder(0, 0, 0, 4, Color.darkGray),BorderFactory.createEmptyBorder(4,4,4,4)));

        buttonCustomer = new PanelButton(BUTTON_CUSTOMER_LABEL, new ImageIcon(getClass().getResource(IconConstants.CUSTOMER_ICON)));
//        buttonCustomer.setHorizontalAlignment(SwingConstants.CENTER);
//        buttonCustomer.setVerticalAlignment(SwingConstants.CENTER);
        buttonSales = new PanelButton(BUTTON_SALES_LABEL, new ImageIcon(getClass().getResource(IconConstants.SALES_ICON)));
        buttonSupplier = new PanelButton(BUTTON_SUPPLIER_LABEL, new ImageIcon(getClass().getResource(IconConstants.SUPPLIER_ICON)));
        buttonStock = new PanelButton(Constants.BUTTON_STOCK_LABEL, new ImageIcon(getClass().getResource(IconConstants.STOCK_ICON)));
        buttonMedicine = new PanelButton(Constants.BUTTON_MEDICINE_LABEL, new ImageIcon(getClass().getResource(IconConstants.MEDICINE_ICON)));

        add(buttonCustomer);
        add(buttonMedicine);
        add(buttonSales);
        add(buttonStock);
        add(buttonSupplier);
    }

    private void setListeners() {
        buttonSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        buttonSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupplier1ActionPerformed(evt);
            }
        });
    }

    private void buttonSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {
        manager.createSupplierPanel();
        manager.showSupplierPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private class PanelButton extends JButton{

        public PanelButton(String text,ImageIcon icon) {
            super(text, icon);
//            setPreferredSize(new Dimension(138, HEIGHT));
            setMinimumSize(new Dimension(140, 55));
            setMaximumSize(new Dimension(140, 55));
            setBorder(BorderFactory.createEmptyBorder(6,16,6,6));
            setHorizontalAlignment(SwingConstants.LEFT);
            setVerticalAlignment(SwingConstants.CENTER);
            setHorizontalTextPosition(SwingConstants.RIGHT);
            setFont(FONT_SIZE_14_CALIBRI);
        }
        
    }
}
