/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.safapharma.Templates;

import com.safapharma.Helpers.DesignConstants;
import java.awt.Cursor;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Natasha Malik
 */
public class DialogForm extends javax.swing.JDialog {

    /**
     * Creates new form DialogForm
     */
    public DialogForm() {
        initComponents();        
        this.setLocation(160, 50);
        this.setAlwaysOnTop(true);
        this.setModal(true);
        formPanel.setLayout(new GridLayout(0, 2));
        formPanel.setBorder(BorderFactory.createEmptyBorder(4, 12, 4, 12));
    }

    protected JLabel getFormLabel() {
        return formLabel;
    }

    protected JPanel getFormPanel() {
        return formPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        formLabel.setText("jLabel1");

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(formLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel formLabel;
    private javax.swing.JPanel formPanel;
    // End of variables declaration//GEN-END:variables

    protected class FormButton extends JButton {

        public FormButton(String text) {
            super(text);
            init();
        }

        void init() {
            setFont(DesignConstants.FONT_SIZE_14_CALIBRI_BOLD);
        }
    }

    protected class FormText extends JTextField {

        public FormText() {
            super();
            init();
        }

        void init() {
            setFont(DesignConstants.FONT_SIZE_14_CALIBRI);
        }

    }
    
    protected class FormLabel extends JLabel {

        public FormLabel(String text) {
            super(text);
            init();
        }

        void init() {
            setFont(DesignConstants.FONT_SIZE_18_CALIBRI_BOLD);
        }

    }
}
